apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: slurm-exporter
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  name: slurm-exporter
  namespace: prometheus
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: slurm-exporter
  namespaceSelector:
    matchNames:
    - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: slurm-exporter
